# Generated by Django 5.1.6 on 2025-02-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
