# Generated by Django 5.1.6 on 2025-02-18 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_availabilityexception_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_bookings', to='booking.trainer'),
        ),
    ]
